.include <m324pbdef.inc>
  LDI R16,HIGH(RAMEND)
  OUT SPH,R16
  LDI R16,LOW(RAMEND)
  OUT SPL,R16
  LDI R20, 0xFF
  OUT DDRA, R20;make PORTA an output port

OUT PORTB,R16 ; ACTIVATE PULLUPS
LDI R17,$00
OUT DDRB,R17; Set Direction as inputs. PORT B INPUT

Main:
SBIC PINB,0 
CALL LOWTOHIGH

SBIC PINB,1
CALL HIGHTOLOW

rjmp Main

LOWTOHIGH:
ldi r16, 0
out porta,r16
  SBI PORTA,0;set bit PA0
  CALL DELAY;DELAY before next one
  SBI PORTA,1;turn on PA1
  CALL DELAY;DELAY before next one
  SBI PORTA,2;turn on PA2
  CALL DELAY
  SBI PORTA,3
  CALL DELAY
  SBI PORTA,4
  CALL DELAY
  SBI PORTA,5
  CALL DELAY
  SBI PORTA,6
  CALL DELAY
  SBI PORTA,7
  CALL DELAY
  RET

HIGHTOLOW:
ldi r16, 0
out porta,r16
  SBI PORTA,7;set bit PA0
  CALL DELAY;DELAY before next one
  SBI PORTA,6;turn on PA1
  CALL DELAY;DELAY before next one
  SBI PORTA,5;turn on PA2
  CALL DELAY
  SBI PORTA,4
  CALL DELAY
  SBI PORTA,3
  CALL DELAY
  SBI PORTA,2
  CALL DELAY
  SBI PORTA,1
  CALL DELAY
  SBI PORTA,0
  CALL DELAY
  RET


  DELAY: ldi r20,32
  L1: LDI R21, 200
  L2: LDI R22, 250
  L3: NOP
  NOP
  DEC R22
  BRNE L3
  DEC R21
  BRNE L2
  DEC R20
  BRNE L1
  RET
